### PR TITLE
add loader to hiring board

### PR DESCRIPTION
**Pull request by eduavet**

### CODE REVIEW

**Comment by fxfactorial** [comment]
Very good, i will merge but few points. 

1) You forgot to add updated `yarn.lock` file
2) We already use     "react-spinkit": "^3.0.0", that provides a spinner during modal login

**Comment by eduavet** [comment]
1. I did an `npm i --save react-loader` and it got added to `package.json`, what else should have I done to get it to `yarn.lock`?

**Comment by fxfactorial** [comment]
yarn.lock is made by yarn, not by npm

**Comment by eduavet** [comment]
So besides npm I had to also install it through yarn?

**Comment by fxfactorial** [comment]
Also:

3) Maybe make another PR that adds the corresponding one for the freelancers
4) Maybe make sure that the spinner is centered, CSS it isn't. 

No, I would recommend just using yarn, no npm at all.

**Pull request merged**
